Refactor memory management and improve platform compatibility for Windows
sozu-proxy/poule pull request #4
Opened 2024-12-28 17:11 UTC by zelosleone

- Updated `Cargo.toml` to include new Windows-specific dependencies.
- Refactored `GrowableMemoryMap` to enhance memory allocation on Windows, including new methods for growing memory and changing permissions.
- Simplified atomic operations in `PoolInner` for better clarity and performance.
- Removed unused methods in `buffer.rs` to clean up the codebase.
- Improved cross-platform compatibility by consolidating common implementations.
- All test results give passing results

2025-02-10 13:41 UTC, FlorentinDUBOIS requested changes
Besides, @Wonshtrum could you take a look at this pull request.

2025-02-10 13:41 UTC, FlorentinDUBOIS commented on Cargo.toml
> +windows-sys = { version = "0.48", features = ["Win32_Foundation", "Win32_System_Memory"] }
To me, this should be behind a target os criteria as you did in the code

2025-02-11 11:24 UTC, zelosleone commented on Cargo.toml
> +windows-sys = { version = "0.48", features = ["Win32_Foundation", "Win32_System_Memory"] }
Just did, thank you.

2025-04-24 20:31 UTC, zelosleone commented
@FlorentinDUBOIS will this get reviewed?

2025-05-13 12:27 UTC, FlorentinDUBOIS approved these changes

2025-05-13 12:27 UTC, merged